---

- name: services > SSH service in CentOS 6
  service:
    name: sshd
    state: started
    enabled: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: services > SSH service in CentOS 7
  systemd:
    name: sshd
    state: started
    enabled: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

